# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-09 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvsmanager', '0002_auto_20170209_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_info',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 15, 15, 41, 493843), verbose_name='\u4fdd\u5b58\u65e5\u671f'),
        ),
    ]
