# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvsmanager', '0006_auto_20170209_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_info',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
