# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-15 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvsmanager', '0008_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_info',
            name='server_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
