# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvsmanager', '0009_auto_20170215_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_info',
            name='pnb',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
