# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-07 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvsmanager', '0010_auto_20170216_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_ip', models.CharField(max_length=128)),
                ('vip_port', models.CharField(max_length=128, unique=True)),
                ('vip_groupname', models.CharField(max_length=128)),
                ('vip_masterhostname', models.CharField(max_length=128)),
                ('vip_slavehostname', models.CharField(max_length=128)),
                ('app_name', models.CharField(max_length=128)),
                ('idc', models.CharField(max_length=64)),
                ('online', models.CharField(max_length=32)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
