# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvsmanager', '0014_server_info_bondwidth'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_info',
            name='mark',
            field=models.CharField(default='', max_length=128),
        ),
    ]
