# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvsmanager', '0016_auto_20170425_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip_info',
            name='rt_number',
            field=models.CharField(default='', max_length=128),
        ),
    ]
