# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvsmanager', '0017_vip_info_rt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip_info',
            name='app_owner',
            field=models.CharField(default='', max_length=128),
        ),
    ]
